name: Export CV to PDF

on:
  push:
    branches:
      - main
    paths-ignore:
      - "CV.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: pandoc README.md -o CV.pdf --pdf-engine=xelatex

      # - name: Commit PDF
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add CV.pdf
      #     git commit -m "Auto-update CV.pdf"
      #     git push

      - name: Upload CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: CV
          path: CV.pdf
